config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  devise_for :users
  resources :gossips

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user , foreign_key: "user_id"

  validates :content, presence: true,
                     length: { minimum: 5 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :anonymous_username, presence: true,
                        format: { with: /\A[a-zA-Z0-9_]*\z/ }
                        #RegExp du format anonymous_username


  #Pour voir la solution trouvée pour créer une restriction à l'entrée
  #https://stackoverflow.com/questions/28787615/add-invite-code-to-devise
  attr_accessor :secret_code
  validates :secret_code, presence: true,
                          on: :create,
                          inclusion: { in: ["THP"] }

  has_many :gossips

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

before_action :sanitize_devise_params, if: :devise_controller?

#Pour voir la solution trouvée pour créer une restriction à l'entrée
#https://stackoverflow.com/questions/28787615/add-invite-code-to-devise
  protected

  def sanitize_devise_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:anonymous_username, :secret_code])
  end

end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

    def new
      if user_signed_in?
          @gossip = Gossip.new
      else
          #Pour empëcher les petits malins de poster sans s'ëtre connecté !
          redirect_to root_url
          flash[:danger] = "Veuillez vous connecter pour créer un nouveau gossip."
      end
    end

    def create
      @gossip = Gossip.new(gossip_params)
      @gossip.user = current_user
      if @gossip.save
        redirect_to @gossip
      else
        render 'new'
      end
    end

    def show
      @gossip = Gossip.find(params[:id])
    end

    def edit
      @gossip = Gossip.find(params[:id])
      #Condition pour éviter l'édition de gossips dont on n'est pas le creator.
      if @gossip.user.id != current_user.id
        flash[:danger] = 'Accès refusé ! '
        redirect_to root_path
      end
    end

    def update
          @gossip = Gossip.find(params[:id])
          if @gossip.update(gossip_params)
            redirect_to @gossip
          else
            render 'edit'
          end
    end

    def destroy
      @gossip = Gossip.find(params[:id])
      #Condition pour éviter la suppression de gossips dont on n'est pas le creator.
      if @gossip.user.id != current_user.id
        flash[:danger] = 'Ca te dérange ? Y a un problème ? Accès refusé ! '
        redirect_to root_path
      else
        @gossip.destroy
        redirect_to root_path
      end
    end

    private
      def gossip_params
        params.permit(:content)
      end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

def index
    @users = User.all
    @gossips = Gossip.all
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/gossips/_form.html.erb
<% if @gossip.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@gossip.errors.count, "error") %> prohibited
      this article from being saved:
    </h2>
    <ul>
      <% @gossip.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= label_tag 'content', 'La rumeur à balancer' %>
<%= text_area_tag 'content' %>

app/views/gossips/edit.html.erb
<h1>Editer le gossip</h1>

<%= form_tag gossip_path(@gossip), method: :put do %>
  <%= render 'form' %>
  <%= submit_tag "Modifier le gossip"%>
<% end %>

<h3>Effacer à jamais le gossip</h3>
<%= link_to 'Cliquer pour détruire', @gossip, method: :delete %>
<br>
<%= link_to 'Retour', gossip_path %>

app/views/gossips/new.html.erb
<h1> Lancer un nouveau gossip</h1>

<%= form_tag (gossips_path) do %>
  <%= render 'form' %>
<br><br>
<%= submit_tag "Lancer !"%>
<% end %>

app/views/gossips/show.html.erb
Un gossip de <%= @gossip.user.anonymous_username %>
<br><br>
<p>Voilà ce que ça dit : </p>
<%= @gossip.content %>

<br><br>
<p> <%= link_to "Corriger le gossip", edit_gossip_path%></p>
<p> <%= link_to 'Cliquer pour détruire à jamais', gossip_path(@gossip), method: :delete ,
              data: { confirm: 'Etes vous sur ?' }%></p>
<br>
<p> <a href="/">Retourner à l'accueil</a> </p>

app/views/home/index.html.erb
<p> Bonjour <%= if user_signed_in?
  current_user.anonymous_username
end %>
</p>
<p>Bienvenue sur le site des Gossips de THP version 2 !</p>


<br>

<%= if !(user_signed_in?)
    link_to "Créer un compte", new_user_registration_path , class: "btn btn-lg btn-primary"
end %>


<% if user_signed_in? %>
    <p> Voici les derniers gossips :</p>
    <table>
      <tr>
        <th>ID</th>
        <th>Date de création</th>
        <th>L'auteur</th>
        <th>Son gossip</th>
        <th>Son gossip</th>
      </tr>

      <% @gossips.each do |gossip| %>
      <tr>
        <td><%= gossip.id %></td>
        <td><%= gossip.created_at %></td>
        <td><%= gossip.user.anonymous_username %></td>
        <td><%= gossip.content %></td>
        <td><%= link_to "Montrer le gossip", gossip_path(gossip) %></td>
        <td><%= link_to "Editer", edit_gossip_path(gossip) %></td>
        <td><%= link_to 'Detruire', gossip_path(gossip),
                method: :delete,
                data: { confirm: 'Etes vous sûr de votre acte irréversible ?' } %></td>

      </tr>
      <% end %>
    </table>
<br><br>
<% end %>

<br><br>
<p> Retrouvez les codes sources pour recréer ce projet ici :</p>
<p><a href="https://github.com/nicohc/">Lien github</a></p>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Accueil", '/' %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Créer un gossip",  new_gossip_path %>
          </li>
          <li><%= link_to "Edition du compte",  edit_user_registration_path %>
          </li>
          <li><%= link_to "Se déconnecter" , destroy_user_session_path, method: :delete %>
          </li>

        <% else%>
          <li><%= link_to "Se connecter" , new_user_session_path %>
          </li>
          <li><%= link_to "S'inscrire" , new_user_registration_path %>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GossipWithDevise</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="pageprincipale">
      <!-- COde pour afficher un message pop-up de bienvenue après l'inscription -->
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
<!-- Debug mode
      <%= debug(params) if Rails.env.development? %>
-->
    </div>
  </body>
</html>